apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: rtc
data:
  gpu-media-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "GPU Media Processing Dashboard",
        "tags": ["gpu", "webrtc", "latency"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Request Latency P95",
            "type": "stat",
            "targets": [
              {
                "expr": "app_request_latency_p95_seconds * 1000",
                "legendFormat": "P95 Latency (ms)"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "ms",
                "thresholds": {
                  "steps": [
                    {"color": "green", "value": null},
                    {"color": "yellow", "value": 100},
                    {"color": "red", "value": 200}
                  ]
                }
              }
            },
            "gridPos": {"h": 8, "w": 6, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Request Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "rate(app_requests_total[5m])",
                "legendFormat": "Requests/sec"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "reqps"
              }
            },
            "gridPos": {"h": 8, "w": 6, "x": 6, "y": 0}
          },
          {
            "id": 3,
            "title": "GPU Utilization",
            "type": "stat",
            "targets": [
              {
                "expr": "DCGM_FI_DEV_GPU_UTIL",
                "legendFormat": "GPU {{ $labels.gpu }} Util %"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percent",
                "thresholds": {
                  "steps": [
                    {"color": "green", "value": null},
                    {"color": "yellow", "value": 70},
                    {"color": "red", "value": 90}
                  ]
                }
              }
            },
            "gridPos": {"h": 8, "w": 6, "x": 12, "y": 0}
          },
          {
            "id": 4,
            "title": "Active Pods",
            "type": "stat",
            "targets": [
              {
                "expr": "count(up{job=\"gpu-media-app\"} == 1)",
                "legendFormat": "Active Pods"
              }
            ],
            "gridPos": {"h": 8, "w": 6, "x": 18, "y": 0}
          },
          {
            "id": 5,
            "title": "Latency Over Time",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(app_request_latency_seconds_bucket[5m])) * 1000",
                "legendFormat": "P95 Latency"
              },
              {
                "expr": "histogram_quantile(0.50, rate(app_request_latency_seconds_bucket[5m])) * 1000",
                "legendFormat": "P50 Latency"
              }
            ],
            "yAxes": [
              {
                "unit": "ms",
                "label": "Latency (ms)"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8}
          },
          {
            "id": 6,
            "title": "GPU Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "DCGM_FI_DEV_MEM_COPY_UTIL",
                "legendFormat": "GPU {{ $labels.gpu }} Memory Util %"
              }
            ],
            "yAxes": [
              {
                "unit": "percent",
                "label": "Memory Utilization %"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8}
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "10s"
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: rtc
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.0.0
        ports:
        - containerPort: 3000
          name: web
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin123"  # Change in production
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-datasources
        configMap:
          name: grafana-datasources

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: rtc
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: rtc
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    name: web
  type: LoadBalancer
