apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gpu-media-hpa-latency
  namespace: rtc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gpu-media
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: app_latency_p95_seconds
      target:
        type: AverageValue
        averageValue: "0.20"
