apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gpu-media
  namespace: rtc
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: gpu-media
  namespaceSelector:
    matchNames:
      - rtc
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
